name: Run DTR

on:
  schedule:
    # 7:30 AM PST (11:30 PM UTC the previous day)
    - cron: '30 23 * * 0-4'
    # 5:00 PM PST (9:00 AM UTC the same day)
    - cron: '0 9 * * 1-5'
  workflow_dispatch:

jobs:
  process:
    runs-on: windows-latest

    steps:
    - name: Install Chrome
      run: choco install googlechrome -y

    - name: Install ChromeDriver
      run: choco install chromedriver -y

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build the application
      run: dotnet build --configuration Release --no-restore

    - name: Run the executable
      run: |
        $env:AWS_ACCESS_KEY_ID = '${{secrets.AWS_ACCESS_KEY_ID}}'
        $env:AWS_SECRET_ACCESS_KEY = '${{secrets.AWS_SECRET_ACCESS_KEY}}'
        $env:AWS_SNS_ARN = '${{secrets.AWS_SNS_ARN}}'
        $env:PRIMARY_USERNAME = '${{secrets.PRIMARY_USERNAME}}'
        $env:PRIMARY_PASSWORD = '${{secrets.PRIMARY_PASSWORD}}'
        ./bin/Release/net8.0/EmaptaLoginAutomation.exe
      env:
        PERSONAL_AWS_ACCESS_KEY_ID : ${{secrets.AWS_ACCESS_KEY_ID}}
        PERSONAL_AWS_SECRET_ACCESS_KEY : ${{secrets.AWS_SECRET_ACCESS_KEY}}
        PERSONAL_AWS_SNS_ARN : ${{secrets.AWS_SNS_ARN}}
        PRIMARY_USERNAME : ${{secrets.PRIMARY_USERNAME}}
        PRIMARY_PASSWORD : ${{secrets.PRIMARY_PASSWORD}}
